import { ChartBar, TrendUp, UsersThree } from "@phosphor-icons/react/dist/ssr";

import Link from "next/link";

import { getAnalyticsOverview, getAnalyticsStudents } from "@/lib/server-api";

export default async function AnalyticsPage() {
  const [analytics, students] = await Promise.all([getAnalyticsOverview(), getAnalyticsStudents()]);
  return <div className="app-main"><header className="border-b border-twilight/13 pb-8"><p className="eyebrow text-seaweed">Acompañamiento educativo</p><h1 className="display mt-4 text-4xl tracking-[-.055em] sm:text-6xl lg:text-7xl">Entiende dónde reforzar.</h1><p className="pretty-copy mt-5 max-w-xl leading-7 text-twilight/58">Resultados de quizzes, intentos y competencias con mayor dificultad.</p></header><section className="mt-10 grid gap-4 md:grid-cols-3"><article className="surface p-6"><UsersThree size={23} className="text-teal" /><p className="metric-number mt-6 text-4xl font-bold text-twilight">{analytics.students}</p><p className="mt-2 text-sm text-twilight/50">Estudiantes en tu ámbito</p></article><article className="surface p-6"><ChartBar size={23} className="text-teal" /><p className="metric-number mt-6 text-4xl font-bold text-twilight">{analytics.attempts}</p><p className="mt-2 text-sm text-twilight/50">Intentos registrados</p></article><article className="surface p-6"><TrendUp size={23} className="text-teal" /><p className="metric-number mt-6 text-4xl font-bold text-twilight">{analytics.average_score}%</p><p className="mt-2 text-sm text-twilight/50">Promedio de calificación</p></article></section><section className="mt-10 surface p-6 sm:p-8"><p className="eyebrow text-teal">Estudiantes</p><h2 className="display mt-3 text-3xl">Seguimiento individual.</h2><div className="mt-6 grid gap-3">{students.length === 0 ? <p className="text-sm text-twilight/55">Todavía no hay estudiantes en tu ámbito.</p> : students.map((student) => <Link key={student.id} href={`/admin/analytics/students/${student.id}`} className="flex items-center justify-between rounded-xl border border-twilight/10 bg-canvas px-4 py-3 transition hover:border-seaweed/40"><span><span className="block text-sm font-semibold">{student.full_name}</span><span className="mt-1 block text-xs text-twilight/50">{student.attempts} intentos · promedio {student.average_score}%</span></span><span className="text-xs font-bold text-teal">Ver detalle →</span></Link>)}</div></section><section className="mt-10 surface p-6 sm:p-8"><p className="eyebrow text-teal">Falencias agregadas</p><h2 className="display mt-3 text-3xl">Competencias para reforzar.</h2>{analytics.failed_competencies.length === 0 ? <p className="mt-6 text-sm text-twilight/55">Todavía no hay respuestas incorrectas registradas.</p> : <div className="mt-6 grid gap-3">{analytics.failed_competencies.map((item) => <div key={item.competency} className="flex items-center justify-between rounded-xl border border-twilight/10 bg-canvas px-4 py-3"><span className="text-sm font-semibold">{item.competency}</span><span className="metric-number text-sm font-bold text-danger">{item.count} fallos</span></div>)}</div>}</section></div>;
}
