import Link from "next/link";
import { ArrowLeft, ArrowUpRight, BookOpen, Plus } from "@phosphor-icons/react/dist/ssr";

import { getAdminModules } from "@/lib/server-api";

export default async function AdminModulesPage() {
  const modules = await getAdminModules();
  return <div className="app-main"><div className="flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><div><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm text-ink/50 hover:text-ink"><ArrowLeft size={16} /> Dashboard</Link><p className="eyebrow mt-8 text-cobalt">Admin / Biblioteca</p><h1 className="display mt-4 text-5xl tracking-[-.06em] sm:text-7xl">Módulos.</h1><p className="mt-5 max-w-xl leading-7 text-ink/60">Organiza la ruta de aprendizaje y crea los espacios donde vivirán tus lecciones.</p></div><Link href="/admin/modules/new" className="button button-ink button-large"><Plus size={18} weight="bold" /> Nuevo módulo</Link></div><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{modules.map((module, index) => <Link key={module.id} href={`/admin/modules/${module.id}`} className="group flex min-h-[230px] flex-col justify-between rounded-[1.5rem] border border-ink/12 bg-white p-6 transition-transform duration-500 hover:-translate-y-1 hover:border-cobalt/45"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-full bg-ink text-xs font-bold text-lime">{String(index + 1).padStart(2, "0")}</span><span className={`rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-widest ${module.status === "published" ? "bg-lime/35 text-ink" : "bg-ink/7 text-ink/50"}`}>{module.status === "published" ? "Publicado" : module.status === "draft" ? "Borrador" : "Archivado"}</span></div><div><h2 className="display text-2xl tracking-[-.04em]">{module.title}</h2><p className="mt-3 line-clamp-2 text-sm leading-6 text-ink/55">{module.description || "Sin descripción todavía."}</p><div className="mt-5 flex items-center gap-4 text-xs text-ink/45"><span className="flex items-center gap-2"><BookOpen size={15} /> Orden {module.order}</span><span className="ml-auto inline-flex items-center gap-1 font-bold text-cobalt">Ver lecciones <ArrowUpRight size={15} /></span></div></div></Link>)}{modules.length === 0 && <div className="rounded-[1.5rem] border border-dashed border-ink/20 p-10 text-center md:col-span-2 lg:col-span-3"><p className="font-semibold">Todavía no hay módulos.</p><p className="mt-2 text-sm text-ink/50">Crea el primero para empezar a construir la ruta.</p></div>}</div></div>;
}
