import { ArrowLeft, ArrowRight, BookOpen, Plus } from "@phosphor-icons/react/dist/ssr";
import Link from "next/link";

import { StatusBadge } from "@/components/ui/status-badge";
import { getAdminModules } from "@/lib/server-api";

export default async function AdminModulesPage() {
  const modules = await getAdminModules();
  return <div className="app-main"><header className="flex flex-col justify-between gap-8 border-b border-twilight/13 pb-8 sm:flex-row sm:items-end"><div><Link href="/dashboard" className="back-link"><ArrowLeft size={16} /> Volver al dashboard</Link><p className="eyebrow mt-8 text-seaweed">Administración / Biblioteca</p><h1 className="display mt-4 text-5xl tracking-[-.055em] sm:text-7xl">Diseña la ruta.</h1><p className="pretty-copy mt-5 max-w-xl leading-7 text-twilight/58">Organiza los módulos y construye los espacios donde vivirán las experiencias de aprendizaje.</p></div><Link href="/admin/modules/new" className="button button-primary button-large"><Plus size={18} weight="bold" /> Nuevo módulo</Link></header><section className="mt-10"><div className="mb-5 flex items-center justify-between"><p className="eyebrow text-teal">{modules.length} módulos</p><BookOpen size={22} className="text-seaweed" /></div>{modules.length === 0 ? <div className="empty-state"><p className="font-semibold">Todavía no hay módulos.</p><p className="mt-2 text-sm text-twilight/50">Crea el primero para empezar a construir la ruta.</p></div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{modules.map((module) => <Link key={module.id} href={`/admin/modules/${module.id}`} className="group flex min-h-[15rem] flex-col justify-between rounded-[1.35rem] border border-twilight/10 bg-white p-6 transition duration-300 hover:-translate-y-1 hover:border-seaweed/45 hover:shadow-[0_16px_38px_rgba(15,8,75,.08)]"><div className="flex items-start justify-between gap-4"><span className="metric-number text-xs font-bold text-seaweed">/{String(module.order).padStart(2, "0")}</span><StatusBadge status={module.status} /></div><div><h2 className="display text-2xl tracking-[-.035em]">{module.title}</h2><p className="mt-3 line-clamp-2 text-sm leading-6 text-twilight/55">{module.description || "Sin descripción todavía."}</p><span className="mt-5 flex items-center justify-between text-xs font-bold uppercase tracking-[.1em] text-teal">Gestionar lecciones <ArrowRight size={16} className="transition-transform group-hover:translate-x-1" /></span></div></Link>)}</div>}</section></div>;
}
