import { ArrowLeft, ArrowRight, BookOpen, Plus } from "@phosphor-icons/react/dist/ssr";
import Link from "next/link";
import { notFound } from "next/navigation";

import { StatusBadge } from "@/components/ui/status-badge";
import { getAdminModule, getAdminModuleLessons } from "@/lib/server-api";

export default async function AdminModuleDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const [module, lessons] = await Promise.all([getAdminModule(id), getAdminModuleLessons(id)]);
  if (!module) notFound();

  return <div className="app-main"><header className="flex flex-col justify-between gap-8 border-b border-twilight/13 pb-8 sm:flex-row sm:items-end"><div><Link href="/admin/modules" className="back-link"><ArrowLeft size={16} /> Módulos</Link><p className="eyebrow mt-8 text-seaweed">Administración / Módulo</p><div className="mt-4 flex flex-wrap items-center gap-4"><h1 className="display text-5xl tracking-[-.055em] sm:text-7xl">{module.title}</h1><StatusBadge status={module.status} /></div><p className="pretty-copy mt-5 max-w-2xl leading-7 text-twilight/58">{module.description || "Organiza aquí las lecciones que forman esta parte de la ruta."}</p></div><div className="flex flex-wrap gap-3"><Link href={`/admin/assessments/new?target=module&targetId=${module.id}`} className="button button-secondary button-large">Quiz final</Link><Link href={`/admin/lessons/new?module=${module.id}`} className="button button-primary button-large"><Plus size={18} weight="bold" /> Nueva lección</Link></div></header><section className="mt-10"><div className="flex items-center justify-between border-b border-twilight/13 pb-5"><div className="flex items-center gap-3"><BookOpen size={21} className="text-seaweed" /><p className="eyebrow text-teal">{lessons.length} {lessons.length === 1 ? "lección" : "lecciones"}</p></div><span className="text-sm text-twilight/45">Orden de ruta</span></div>{lessons.length === 0 ? <div className="empty-state mt-5"><p className="font-semibold">Este módulo todavía está vacío.</p><p className="mt-2 text-sm text-twilight/50">Crea la primera lección para empezar a construirlo.</p></div> : <div className="mt-5 overflow-hidden rounded-[1.35rem] border border-twilight/10 bg-white">{lessons.map((lesson, index) => <div key={lesson.id} className="grid gap-4 border-b border-twilight/10 px-5 py-5 last:border-b-0 sm:grid-cols-[3rem_1fr_auto_auto] sm:items-center sm:px-7"><span className="metric-number text-xs font-bold text-seaweed">{String(index + 1).padStart(2, "0")}</span><div><h2 className="font-semibold text-twilight">{lesson.title}</h2><p className="mt-1 text-sm text-twilight/50">{lesson.description || "Sin descripción"} · {lesson.estimated_minutes} min</p></div><StatusBadge status={lesson.status} /><span className="flex flex-wrap gap-2"><Link href={`/admin/lessons/${lesson.id}`} className="button button-quiet w-fit">Editar <ArrowRight size={15} /></Link><Link href={`/admin/assessments/new?target=lesson&targetId=${lesson.id}`} className="button button-quiet w-fit">Quiz</Link></span></div>)}</div>}</section></div>;
}
